### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms' 

### ISSUE THREAD

**Issue by lulunac27a** [coloria-dev/coloria#209]
When I run `import coloria` in python, I get an error saying `AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'` and the python program exits unexpectedly.

**Comment by nschloe** [comment]
This is perhaps unrelated to coloria itself. You could try
```
python3 -m pip install --upgrade pip
```
and
```
python3 -m pip install --upgrade openssl
```

**Comment by nschloe** [comment]
Closing for lack of feedback. Let me know if you have any more problems!
